USE UCNAirlines;
INSERT INTO Country VALUES ('Denmark');
INSERT INTO Country VALUES ('Greenland');

INSERT INTO City_Zip_Code VALUES ('9000', 'Aalborg', 1);
INSERT INTO City_Zip_Code VALUES ('7190', 'Billund', 1);

INSERT INTO City_Zip_Code VALUES ('3900', 'Nuuk', 2);
INSERT INTO City_Zip_Code VALUES ('3952', 'Ilulissat', 2);
INSERT INTO City_Zip_Code VALUES ('3910', 'Kangerlussuaq', 2);

INSERT INTO Airplane VALUES ('UCN1', 'UCN', 2, 2);
INSERT INTO Airplane VALUES ('UCN2', 'UCN', 2, 2);
INSERT INTO Airplane VALUES ('UCN3', 'UCN', 2, 2);
INSERT INTO Airplane VALUES ('UCN4', 'UCN', 30, 6);

INSERT INTO Airport VALUES ('EKYT', 'Aalborg Airport', '9000');
INSERT INTO Airport VALUES ('EKBI', 'Billund Airport', '7190');
INSERT INTO Airport VALUES ('BGGH', 'Nuuk Airport', '3900');
INSERT INTO Airport VALUES ('BGJN', 'Ilulissat Airport', '3952');
INSERT INTO Airport VALUES ('BGSF', 'Kangerlussuaq Airport', '3910');

INSERT INTO Flight_Route VALUES ('EKYT', 'BGGH');
INSERT INTO Flight_Route VALUES ('BGGH', 'EKYT');
INSERT INTO Flight_Route VALUES ('BGJN', 'EKYT');
INSERT INTO Flight_Route VALUES ('BGSF', 'EKBI');

INSERT INTO Flight VALUES ('01/06/2025 12:00', 'UCN1', 1);
INSERT INTO Flight VALUES ('12/12/2026 12:00', 'UCN4', 2);

INSERT INTO Booking VALUES (1);

INSERT INTO Passenger VALUES ('12345678', 'John', 'Johnsen', '01/01/1990');
INSERT INTO Passenger VALUES ('87654321', 'Hans', 'Hansen', '12/12/1950');

INSERT INTO Seat VALUES ('1A', '12345678', 1);
INSERT INTO Seat VALUES ('1B', '87654321', 1);
INSERT INTO Seat VALUES ('2A', null, 1);
INSERT INTO Seat VALUES ('2B', null, 1);

INSERT INTO Seat VALUES ('1A', null, 2);
INSERT INTO Seat VALUES ('1B', null, 2);
INSERT INTO Seat VALUES ('1C', null, 2);
INSERT INTO Seat VALUES ('1D', null, 2);
INSERT INTO Seat VALUES ('1E', null, 2);
INSERT INTO Seat VALUES ('1F', null, 2);
INSERT INTO Seat VALUES ('2A', null, 2);
INSERT INTO Seat VALUES ('2B', null, 2);
INSERT INTO Seat VALUES ('2C', null, 2);
INSERT INTO Seat VALUES ('2D', null, 2);
INSERT INTO Seat VALUES ('2E', null, 2);
INSERT INTO Seat VALUES ('2F', null, 2);
INSERT INTO Seat VALUES ('3A', null, 2);
INSERT INTO Seat VALUES ('3B', null, 2);
INSERT INTO Seat VALUES ('3C', null, 2);
INSERT INTO Seat VALUES ('3D', null, 2);
INSERT INTO Seat VALUES ('3E', null, 2);
INSERT INTO Seat VALUES ('3F', null, 2);
INSERT INTO Seat VALUES ('4A', null, 2);
INSERT INTO Seat VALUES ('4B', null, 2);
INSERT INTO Seat VALUES ('4C', null, 2);
INSERT INTO Seat VALUES ('4D', null, 2);
INSERT INTO Seat VALUES ('4E', null, 2);
INSERT INTO Seat VALUES ('4F', null, 2);
INSERT INTO Seat VALUES ('5A', null, 2);
INSERT INTO Seat VALUES ('5B', null, 2);
INSERT INTO Seat VALUES ('5C', null, 2);
INSERT INTO Seat VALUES ('5D', null, 2);
INSERT INTO Seat VALUES ('5E', null, 2);
INSERT INTO Seat VALUES ('5F', null, 2);
INSERT INTO Seat VALUES ('6A', null, 2);
INSERT INTO Seat VALUES ('6B', null, 2);
INSERT INTO Seat VALUES ('6C', null, 2);
INSERT INTO Seat VALUES ('6D', null, 2);
INSERT INTO Seat VALUES ('6E', null, 2);
INSERT INTO Seat VALUES ('6F', null, 2);
INSERT INTO Seat VALUES ('7A', null, 2);
INSERT INTO Seat VALUES ('7B', null, 2);
INSERT INTO Seat VALUES ('7C', null, 2);
INSERT INTO Seat VALUES ('7D', null, 2);
INSERT INTO Seat VALUES ('7E', null, 2);
INSERT INTO Seat VALUES ('7F', null, 2);
INSERT INTO Seat VALUES ('8A', null, 2);
INSERT INTO Seat VALUES ('8B', null, 2);
INSERT INTO Seat VALUES ('8C', null, 2);
INSERT INTO Seat VALUES ('8D', null, 2);
INSERT INTO Seat VALUES ('8E', null, 2);
INSERT INTO Seat VALUES ('8F', null, 2);
INSERT INTO Seat VALUES ('9A', null, 2);
INSERT INTO Seat VALUES ('9B', null, 2);
INSERT INTO Seat VALUES ('9C', null, 2);
INSERT INTO Seat VALUES ('9D', null, 2);
INSERT INTO Seat VALUES ('9E', null, 2);
INSERT INTO Seat VALUES ('9F', null, 2);
INSERT INTO Seat VALUES ('10A', null, 2);
INSERT INTO Seat VALUES ('10B', null, 2);
INSERT INTO Seat VALUES ('10C', null, 2);
INSERT INTO Seat VALUES ('10D', null, 2);
INSERT INTO Seat VALUES ('10E', null, 2);
INSERT INTO Seat VALUES ('10F', null, 2);
INSERT INTO Seat VALUES ('11A', null, 2);
INSERT INTO Seat VALUES ('11B', null, 2);
INSERT INTO Seat VALUES ('11C', null, 2);
INSERT INTO Seat VALUES ('11D', null, 2);
INSERT INTO Seat VALUES ('11E', null, 2);
INSERT INTO Seat VALUES ('11F', null, 2);
INSERT INTO Seat VALUES ('12A', null, 2);
INSERT INTO Seat VALUES ('12B', null, 2);
INSERT INTO Seat VALUES ('12C', null, 2);
INSERT INTO Seat VALUES ('12D', null, 2);
INSERT INTO Seat VALUES ('12E', null, 2);
INSERT INTO Seat VALUES ('12F', null, 2);
INSERT INTO Seat VALUES ('13A', null, 2);
INSERT INTO Seat VALUES ('13B', null, 2);
INSERT INTO Seat VALUES ('13C', null, 2);
INSERT INTO Seat VALUES ('13D', null, 2);
INSERT INTO Seat VALUES ('13E', null, 2);
INSERT INTO Seat VALUES ('13F', null, 2);
INSERT INTO Seat VALUES ('14A', null, 2);
INSERT INTO Seat VALUES ('14B', null, 2);
INSERT INTO Seat VALUES ('14C', null, 2);
INSERT INTO Seat VALUES ('14D', null, 2);
INSERT INTO Seat VALUES ('14E', null, 2);
INSERT INTO Seat VALUES ('14F', null, 2);
INSERT INTO Seat VALUES ('15A', null, 2);
INSERT INTO Seat VALUES ('15B', null, 2);
INSERT INTO Seat VALUES ('15C', null, 2);
INSERT INTO Seat VALUES ('15D', null, 2);
INSERT INTO Seat VALUES ('15E', null, 2);
INSERT INTO Seat VALUES ('15F', null, 2);
INSERT INTO Seat VALUES ('16A', null, 2);
INSERT INTO Seat VALUES ('16B', null, 2);
INSERT INTO Seat VALUES ('16C', null, 2);
INSERT INTO Seat VALUES ('16D', null, 2);
INSERT INTO Seat VALUES ('16E', null, 2);
INSERT INTO Seat VALUES ('16F', null, 2);
INSERT INTO Seat VALUES ('17A', null, 2);
INSERT INTO Seat VALUES ('17B', null, 2);
INSERT INTO Seat VALUES ('17C', null, 2);
INSERT INTO Seat VALUES ('17D', null, 2);
INSERT INTO Seat VALUES ('17E', null, 2);
INSERT INTO Seat VALUES ('17F', null, 2);
INSERT INTO Seat VALUES ('18A', null, 2);
INSERT INTO Seat VALUES ('18B', null, 2);
INSERT INTO Seat VALUES ('18C', null, 2);
INSERT INTO Seat VALUES ('18D', null, 2);
INSERT INTO Seat VALUES ('18E', null, 2);
INSERT INTO Seat VALUES ('18F', null, 2);
INSERT INTO Seat VALUES ('19A', null, 2);
INSERT INTO Seat VALUES ('19B', null, 2);
INSERT INTO Seat VALUES ('19C', null, 2);
INSERT INTO Seat VALUES ('19D', null, 2);
INSERT INTO Seat VALUES ('19E', null, 2);
INSERT INTO Seat VALUES ('19F', null, 2);
INSERT INTO Seat VALUES ('20A', null, 2);
INSERT INTO Seat VALUES ('20B', null, 2);
INSERT INTO Seat VALUES ('20C', null, 2);
INSERT INTO Seat VALUES ('20D', null, 2);
INSERT INTO Seat VALUES ('20E', null, 2);
INSERT INTO Seat VALUES ('20F', null, 2);
INSERT INTO Seat VALUES ('21A', null, 2);
INSERT INTO Seat VALUES ('21B', null, 2);
INSERT INTO Seat VALUES ('21C', null, 2);
INSERT INTO Seat VALUES ('21D', null, 2);
INSERT INTO Seat VALUES ('21E', null, 2);
INSERT INTO Seat VALUES ('21F', null, 2);
INSERT INTO Seat VALUES ('22A', null, 2);
INSERT INTO Seat VALUES ('22B', null, 2);
INSERT INTO Seat VALUES ('22C', null, 2);
INSERT INTO Seat VALUES ('22D', null, 2);
INSERT INTO Seat VALUES ('22E', null, 2);
INSERT INTO Seat VALUES ('22F', null, 2);
INSERT INTO Seat VALUES ('23A', null, 2);
INSERT INTO Seat VALUES ('23B', null, 2);
INSERT INTO Seat VALUES ('23C', null, 2);
INSERT INTO Seat VALUES ('23D', null, 2);
INSERT INTO Seat VALUES ('23E', null, 2);
INSERT INTO Seat VALUES ('23F', null, 2);
INSERT INTO Seat VALUES ('24A', null, 2);
INSERT INTO Seat VALUES ('24B', null, 2);
INSERT INTO Seat VALUES ('24C', null, 2);
INSERT INTO Seat VALUES ('24D', null, 2);
INSERT INTO Seat VALUES ('24E', null, 2);
INSERT INTO Seat VALUES ('24F', null, 2);
INSERT INTO Seat VALUES ('25A', null, 2);
INSERT INTO Seat VALUES ('25B', null, 2);
INSERT INTO Seat VALUES ('25C', null, 2);
INSERT INTO Seat VALUES ('25D', null, 2);
INSERT INTO Seat VALUES ('25E', null, 2);
INSERT INTO Seat VALUES ('25F', null, 2);
INSERT INTO Seat VALUES ('26A', null, 2);
INSERT INTO Seat VALUES ('26B', null, 2);
INSERT INTO Seat VALUES ('26C', null, 2);
INSERT INTO Seat VALUES ('26D', null, 2);
INSERT INTO Seat VALUES ('26E', null, 2);
INSERT INTO Seat VALUES ('26F', null, 2);
INSERT INTO Seat VALUES ('27A', null, 2);
INSERT INTO Seat VALUES ('27B', null, 2);
INSERT INTO Seat VALUES ('27C', null, 2);
INSERT INTO Seat VALUES ('27D', null, 2);
INSERT INTO Seat VALUES ('27E', null, 2);
INSERT INTO Seat VALUES ('27F', null, 2);
INSERT INTO Seat VALUES ('28A', null, 2);
INSERT INTO Seat VALUES ('28B', null, 2);
INSERT INTO Seat VALUES ('28C', null, 2);
INSERT INTO Seat VALUES ('28D', null, 2);
INSERT INTO Seat VALUES ('28E', null, 2);
INSERT INTO Seat VALUES ('28F', null, 2);
INSERT INTO Seat VALUES ('29A', null, 2);
INSERT INTO Seat VALUES ('29B', null, 2);
INSERT INTO Seat VALUES ('29C', null, 2);
INSERT INTO Seat VALUES ('29D', null, 2);
INSERT INTO Seat VALUES ('29E', null, 2);
INSERT INTO Seat VALUES ('29F', null, 2);
INSERT INTO Seat VALUES ('30A', null, 2);
INSERT INTO Seat VALUES ('30B', null, 2);
INSERT INTO Seat VALUES ('30C', null, 2);
INSERT INTO Seat VALUES ('30D', null, 2);
INSERT INTO Seat VALUES ('30E', null, 2);
INSERT INTO Seat VALUES ('30F', null, 2);

INSERT INTO PassengerBooking VALUES (1, '12345678');
INSERT INTO PassengerBooking VALUES (1, '87654321');





